# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: Notable Changes 🎉
      labels:
        - Semver-Minor
        - enhancement
    - title: Other Changes
      labels:
        - '*'
